/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddBookmark: typeof import('./components/bookmarks/AddBookmark.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    BookmarkList: typeof import('./components/bookmarks/BookmarkList.vue')['default']
    BookmarkListItem: typeof import('./components/bookmarks/BookmarkListItem.vue')['default']
    EditBookmark: typeof import('./components/bookmarks/EditBookmark.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
